package config

type V1_ConfigSchema struct {
	// TODO: add metadata object here
	App App `json:"app" yaml:"app"`
}

type Listener string

type App struct {
	Name string `json:"name" yaml:"name"`
	// TODO: Perhaps add a metadata section here which is auto-generated by the sinkplot
	// to add things like last_updated, revision number, etc
	Listeners []int   `json:"listeners" yaml:"listeners"`
	Routes    []Route `json:"routes" yaml:"routes"`
	Sinks     []Sink  `json:"sinks" yaml:"sinks"`
}

type Route struct {
	Endpoint string    `json:"endpoint" yaml:"endpoint"`
	Methods  *[]string `json:"methods,omitempty" yaml:"methods,omitempty"`
	Match    *string   `json:"match,omitempty" yaml:"match,omitempty"` // exact | prefix | regex, defaults to exact
	Sink     string    `json:"sink" yaml:"sink"`
}

type Sink struct {
	Name      string     `json:"name" yaml:"name"`
	Upstreams []Upstream `json:"upstreams" yaml:"upstreams"`
}

type Upstream struct {
	Address string `json:"address" yaml:"address"`
	Port    int    `json:"port" yaml:"port"`
	Weight  *int   `json:"weight,omitempty" yaml:"weight,omitempty"`
}
