openapi: 3.1.0
info:
  title: Reverse Proxy Configuration Schema
  version: 1.0.0

paths: {}

components:
  schemas:
    Config:
      type: object
      required: [app]
      properties:
        app:
          $ref: '#/components/schemas/App'

    App:
      type: object
      required: [name, listeners, routes, sinks]
      properties:
        name:
          type: string
          minLength: 1
        listeners:
          type: array
          items:
            type: integer
            minimum: 1
            maximum: 65535
          minItems: 1
        routes:
          type: array
          items:
            $ref: '#/components/schemas/Route'
          minItems: 1
        sinks:
          type: array
          items:
            $ref: '#/components/schemas/Sink'
          minItems: 1

    Route:
      type: object
      required: [name, matchers]
      properties:
        name:
          type: string
          minLength: 1
        matchers:
          type: array
          items:
            $ref: '#/components/schemas/Matcher'
          minItems: 1

    Matcher:
      type: object
      required: [endpoint, methods, match, sink]
      properties:
        endpoint:
          type: string
          pattern: '^/.*'
        methods:
          type: array
          items:
            $ref: '#/components/schemas/HttpMethod'
          minItems: 1
        match:
          type: string
          enum: [exact, prefix]
        sink:
          type: string
          minLength: 1

    Sink:
      type: object
      required: [name, upstreams]
      properties:
        name:
          type: string
          minLength: 1
        upstreams:
          type: array
          items:
            $ref: '#/components/schemas/Upstream'
          minItems: 1

    Upstream:
      type: object
      required: [address, port, weight]
      properties:
        address:
          type: string
          format: ipv4
        port:
          type: integer
          minimum: 1
          maximum: 65535
        weight:
          type: integer
          minimum: 1

    HttpMethod:
      type: string
      enum:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
        - HEAD
